language: java
jdk:
  - openjdk8
# git strips the wrapper jar file so we have to force its download during the build
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  env:
      - MAVEN_VERSION=3.2.5
      - MAVEN_VERSION=3.3.9
    install:
      - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
      - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
    script: "./mvnw --show-version --errors --batch-mode -Prun-its clean verify"